version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: book-store-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DATABASE: bookstore
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: --bind_ip_all

volumes:
  mongodb_data: